### ISSUE TITLE
"Print services" button on shortlist does not work

### ISSUE THREAD

**Issue by AyupMike** [RoyalBoroughKingston/ck-frontend#106] opened 2018-09-11 07:53 UTC
- There should be a print-friendly style sheet on this page which removes the global header/footer and has some basic layout styling for the services listed.
- The "Print services" button should also bring up the print dialog

**Comment by seanjessen** [comment] 2018-09-11 09:41
This is duplicate of #55 - sitewide print functionality

**Closed** 2018-09-11 19:12 UTC
Labels: Frontend
